### ISSUE TITLE
Error when merging two mp4 files (with audio builtin)

### ISSUE THREAD

**Issue by Znote** [tngaspar/automerge-video-audio#2]
I am trying to merge 2 .mp4 files into 1. The Audio is built in so I have no files in the music folder. 
```
py .\main.py
Traceback (most recent call last):
  File "automerge-video-audio-main\main.py", line 31, in <module>
    audioClips = CompositeAudioClip([audio[0].set_start(audio[1]).audio_fadein(5).audio_fadeout(5) for audio in audios])
  File "Python310\lib\site-packages\moviepy\audio\AudioClip.py", line 287, in __init__
    self.nchannels = max([c.nchannels for c in self.clips])
ValueError: max() arg is an empty sequence
```

Using VLC media player, I extracted out the .mp3 files and put them in the music folder. Tedious and uneccesary, but I got past this error and into the next one:
```
py .\main.py
Traceback (most recent call last):
  File "C:\Users\Stefan\Documents\tmp\DVD\automerge-video-audio-main\main.py", line 22, in <module>
    audios.append([AudioFileClip(audio), 0 , audioDetails.tag.title, audioDetails.tag.artist, audioDetails.tag.album])
AttributeError: 'NoneType' object has no attribute 'title'
```
Looks like the script will crash for just missing some metadata?

Changed the audio loop to accomodate default values:
```py
for audio in audio_files :
   audioDetails = eyed3.load(audio)
   tagInfo = {
      "title": "no title", 
      "artist": "no artist", 
      "album": "no album"
   }
   if audioDetails.tag != None :
      tagInfo["title"] = audioDetails.tag.title if audioDetails.tag.title != None else "no title"
      tagInfo["artist"] = audioDetails.tag.artist if audioDetails.tag.artist != None else "no artist"
      tagInfo["album"] = audioDetails.tag.album if audioDetails.tag.album != None else "no album"
   if audioNum ==1:
      audios.append([AudioFileClip(audio), 0 , tagInfo["title"], tagInfo["artist"], tagInfo["album"]])
   else:
      audios.append([AudioFileClip(audio), currentDuration, tagInfo["title"], tagInfo["artist"], tagInfo["album"]])
   currentDuration = currentDuration + audios[-1][0].duration-5
   audioNum = audioNum + 1
```

```
py .\main.py
Audio length:  24.225666666666665
Video length:  24.225666666666665
Moviepy - Building video output/final_14.24.10_23.07.2022.mp4.
MoviePy - Writing audio in final_14.24.10_23.07.2022TEMP_MPY_wvf_snd.mp3
MoviePy - Done.
Moviepy - Writing video output/final_14.24.10_23.07.2022.mp4

Moviepy - Done !
Moviepy - video ready output/final_14.24.10_23.07.2022.mp4
```

Input video:
![image](https://user-images.githubusercontent.com/1552144/180605090-10590dd2-383c-4a1d-8148-26a73dc33043.png)

Output video:
![image](https://user-images.githubusercontent.com/1552144/180605160-c74d007e-d3a6-40ca-93f5-36f8a2952803.png)

Looks like the aspect ratio got broken
The audio gets desync the further along the video you go. 
Changing 24 fps to 25 fps (to match original files) didnt seem to fix it. 

Giving up, why does merging 2 mp4 files have to be so hard. :P

Edit: I eventually gave in and just downloaded and installed [Shotcut](https://github.com/mltframework/shotcut) video editor, added both files to the timeline and exported it. That worked flawlessly. I just though it unnecessary to install an entire video editor program just to merge 2 files together. Which is why I tried this script.

**Comment by tngaspar** [comment]
I had a look into this. Here are a few points:

Regarding the metadata extraction. You are correct, the script breaks if  the files do not have metadata. I will be removing this dependency in a future commit.

This script is not ideal for your use case. I will rewrite the README and be more specific.

The merge you want can be achieved with less code.
Even though you were able to do the task with a video editor, I threw something together for future reference:

``` python
import os
from moviepy.editor import VideoFileClip, concatenate_videoclips

# setup - adjust this values
video_fade_secs = 1 # set length of fadein and fade out between videos in seconds
audio_fade_secs = 1
video_directory='video'

# get .mp4 files from directory
video_files = [video_directory+'/'+file for file in os.listdir(video_directory) if file.endswith(".mp4")]

# create list of clips
videos = []
for video in video_files :
   videos.append(VideoFileClip(video))

# apply fade effects
videos = [video.fadein(video_fade_secs).fadeout(video_fade_secs).audio_fadein(audio_fade_secs).audio_fadeout(audio_fade_secs) for video in videos]

# merge clips
videoclips = concatenate_videoclips(videos , method = 'compose')

# write to final .mp4
videoclips.write_videofile('final_video.mp4')
```
This will merge all videos in the `video_directory` preserving the audio. `video_fade_secs` and `audio_fade_secs` help make the transitions between clips smoother.

As for the aspect ratio, I was not able to reproduce the issue. 
When I tried to merge 2 videos with different aspect ratios the second video got corrupted. Changing the `concatenate_videoclips` method argument from `'chain'` to `'compose'` fixed this.
